name: Lint

on:
  workflow_dispatch

jobs:

  clojure:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.3.1463
          clj-kondo: 2022.10.05

      - name: Lint
        run: clj-kondo --lint deps.edn src resources test
